# Lecture 04의 데모

### Lecture 04의 데모에 대한 코드

참고자료: https://github.com/data-8/materials-sp22/blob/main/lec/lec05.ipynb

In [1]:
import os
from google.colab import drive

drive.mount('/content/gdrive')

%cd /content/gdrive/MyDrive/ITEC419-fa22/lec

Mounted at /content/gdrive
/content/gdrive/MyDrive/ITEC419-fa22/lec


In [2]:
from datascience import *
import numpy as np

## Ranges

In [8]:
# 앞에서 배웠던 make_array를 이용한 ndarray 만들기
make_array(0,1,2,3,4,5,6)

array([0, 1, 2, 3, 4, 5, 6])

In [10]:
# 위의 예시처럼 동일한 ndarray 만들기
# end-1까지 생성
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [11]:
# np.arange(start, end)
# end-1까지 출력
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [12]:
# 세번재 인자는 step
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
np.arange(0,1,0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [15]:
nba = Table.read_table('nba_salaries.csv').where('season', 2020).drop('season')
warriors = nba.where('team', 'Golden State Warriors')


In [17]:
# 0부터 시작해서 특정행을 인덱스를 통해서 가져옴
# 앞의 t.column(label)과 t.select(label)과 구분하자
warriors.take(0)

rank | name          | position | team                  | salary
1    | Stephen Curry | PG       | Golden State Warriors | 40231758

In [21]:
# take 괄호 자리에 array를 넣음으로서 여러 행을 가져올 수 있음
warriors.take(np.arange(3))

rank | name           | position | team                  | salary
1    | Stephen Curry  | PG       | Golden State Warriors | 40231758
13   | Klay Thompson  | SG       | Golden State Warriors | 32742000
60   | Draymond Green | PF       | Golden State Warriors | 18539130

In [25]:
# warrior 테이블에 0-4에 해당하는 행에서의 salary 부분을 array로 가져와서 더해라
np.sum(warriors.take(np.arange(5)).column('salary'))

98154597

## Ways to Create a Table

### Creating a Table from Scratch

In [26]:
streets = make_array('Bancroft', 'Durant', 'Channing', 'Haste')
streets

array(['Bancroft', 'Durant', 'Channing', 'Haste'],
      dtype='<U8')

In [27]:
Table()

In [28]:
# Table().with_column(Label이름, array)해서 테이블에 추가함
southside = Table().with_column('Streets', streets)
southside

Streets
Bancroft
Durant
Channing
Haste

In [29]:
southside.with_column('Blocks from campus', np.arange(4))

Streets  | Blocks from campus
Bancroft | 0
Durant   | 1
Channing | 2
Haste    | 3

In [30]:
southside

Streets
Bancroft
Durant
Channing
Haste

In [31]:
southside = southside.with_column('Blocks from campus', np.arange(4))
southside

Streets  | Blocks from campus
Bancroft | 0
Durant   | 1
Channing | 2
Haste    | 3

In [32]:
# 괄호를 길게 늘여서 여러개를 한번에 작성할 수 있음 -> 가독성 좋음
Table().with_columns(
    'Streets', streets,
    'Blocks from campus', np.arange(4)
)

Streets  | Blocks from campus
Bancroft | 0
Durant   | 1
Channing | 2
Haste    | 3

### Reading a Table from a File

In [ ]:
Table.read_table('du_bois.csv')

**Discussion**: Which group ("CLASS") spent the highest percentage on rent?

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Discussion Question: NBA Salaries

In [ ]:
nba = Table.read_table('nba_salaries.csv')
nba.show(3)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

**Question (a)**: Create an array containing the names of all point guards (PG) who made more than $15M.

**Question (b)**: After evaluating these two expressions in order, what’s the result of the second one?

    nba.drop('position')
    nba.num_columns

**Question (c)**: Who gets the highest salary among non-point guard players?

In [ ]:
nba.where('position', are.not_equal_to('PG')).sort('salary', descending=True).column('name').item(0)

'Kevin Durant'

**Question (d)**: Create an array containing the names of the most frequently selected players in the annual salary top.

In [ ]:
# 각 연도에서 top 1 랭크인 사람을 보여달라.
nba.where('rank', are.equal_to(1))

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
1    | Kevin Garnett    | PF       | Minnesota Timberwolves | 19600000 | 2001
1    | Kevin Garnett    | PF       | Minnesota Timberwolves | 22400000 | 2002
1    | Kevin Garnett    | PF       | Minnesota Timberwolves | 25200000 | 2003
1    | Kevin Garnett    | PF       | Minnesota Timberwolves | 28000000 | 2004
1    | Shaquille O'Neal | C        | Miami Heat             | 29464000 | 2005
1    | Shaquille O'Neal | C        | Miami Heat             | 20000000 | 2006
1    | Kevin Garnett    | PF       | Minnesota Timberwolves | 21000000 | 2007
1    | Kevin Garnett    | PF       | Boston Celtics         | 23751934 | 2008
1    | Kevin Garnett    | PF       | Boston Celtics         | 24751934 | 2009
... (11 rows omitted)

In [ ]:
# group(name)은 동일한 이름에대해 카운트를 세서 보여줌
top_player_of_year = nba.where('rank', 1).group('name').sort('count', descending=True)
top_player_of_year

name             | count
Kevin Garnett    | 7
Kobe Bryant      | 7
Shaquille O'Neal | 3
Stephen Curry    | 3
LeBron James     | 1

In [ ]:
# 제일 큰 count 값에 대해서 뽑기 -> 뒤에 column 사용해서 이름만 뽑기
top_player_of_year.where('count', top_player_of_year.first('count')).column('name')

array(['Kevin Garnett', 'Kobe Bryant'],
      dtype='<U16')

**Question (e)**: Create an array containing the names of the most frequently selected players in the annual salary top 10.

In [ ]:
top10_player_of_year = nba.where('rank', are.below(10)).group('name').sort('count', descending=True)
top10_player_of_year

name             | count
Kevin Garnett    | 11
Kobe Bryant      | 11
Shaquille O'Neal | 11
LeBron James     | 7
Tim Duncan       | 7
Carmelo Anthony  | 6
Allen Iverson    | 5
Dikembe Mutombo  | 5
Dirk Nowitzki    | 5
Jermaine O'Neal  | 5
... (52 rows omitted)

In [ ]:
top10_player_of_year.where('count', top10_player_of_year.first('count')).column('name')

array(['Kevin Garnett', 'Kobe Bryant', "Shaquille O'Neal"],
      dtype='<U19')

## Census

In [ ]:
full = Table.read_table('nc-est2019-agesex-res.csv')
full

SEX  | AGE  | CENSUS2010POP | ESTIMATESBASE2010 | POPESTIMATE2010 | POPESTIMATE2011 | POPESTIMATE2012 | POPESTIMATE2013 | POPESTIMATE2014 | POPESTIMATE2015 | POPESTIMATE2016 | POPESTIMATE2017 | POPESTIMATE2018 | POPESTIMATE2019
0    | 0    | 3944153       | 3944160           | 3951430         | 3963092         | 3926570         | 3931258         | 3954787         | 3983981         | 3954773         | 3893990         | 3815343         | 3783052
0    | 1    | 3978070       | 3978090           | 3957730         | 3966225         | 3977549         | 3942698         | 3948891         | 3973133         | 4002903         | 3972711         | 3908830         | 3829599
0    | 2    | 4096929       | 4096939           | 4090621         | 3970654         | 3978925         | 3991740         | 3958711         | 3966321         | 3991349         | 4020045         | 3987032         | 3922044
0    | 3    | 4119040       | 4119051           | 4111688         | 4101644         | 3981531         | 3991017         | 4005928         | 3974351         | 3982984         | 4006946         | 4033038         | 3998665
0    | 4    | 4063170       | 4063186           | 4077346         | 4121488         | 4111490         | 3992502         | 4004032         | 4020292         | 3989750         | 3997280         | 4018719         | 4043323
0    | 5    | 4056858       | 4056872           | 4064521         | 4087054         | 4131049         | 4121876         | 4004576         | 4017589         | 4035033         | 4003452         | 4008443         | 4028281
0    | 6    | 4066381       | 4066412           | 4072904         | 4074531         | 4096631         | 4141126         | 4133372         | 4017388         | 4031568         | 4048018         | 4014057         | 4017227
0    | 7    | 4030579       | 4030594           | 4042990         | 4082821         | 4084175         | 4106756         | 4152666         | 4145872         | 4030888         | 4044139         | 4058370         | 4022319
0    | 8    | 4046486       | 4046497           | 4025501         | 4052773         | 4092559         | 4094513         | 4118349         | 4165033         | 4158848         | 4042924         | 4054236         | 4066194
0    | 9    | 4148353       | 4148369           | 4125312         | 4035319         | 4062726         | 4103052         | 4106068         | 4130887         | 4177895         | 4170813         | 4053179         | 4061874
... (296 rows omitted)

In [ ]:
partial = full.select('SEX','AGE','POPESTIMATE2014','POPESTIMATE2019')
partial.show(3)

In [ ]:
us_pop = partial.relabled(2, '2014')

AttributeError: ignored

In [ ]:
us_pop.where('AGE',are.above_or_equal_to(80)).sort('AGE')

In [ ]:
us_pop.where('AGE',are.above_or_equal_to(99)).sort('AGE')